apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
  namespace: apps
stringData:
  ENV: "dev"
  SECRET_KEY: "kjguyfdhgvlkjoihiubjn"
  ENROLL_SECRET_KEY: "Eg=C}​k!5]YG`d{​*`#dDZd4=*#"
  ENROLL_SECURITY_PASSWORD_SALT: "Eg=C}​k!5]YG`d{​*`#dDZd4=*#dsad#$$%sfdfs"
  MONGO_URI: "mongodb://rm-portal-mongo-user:^ccJi72328Bk@mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017/rm_portal?authSource=admin"
  AWS_ACCESS_KEY: "AKIAYOG5QD4ADGUEYDEI"
  AWS_SECRET_KEY: "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"
  AWS_REGION: "ap-south-1"
  AWS_BUCKET_NAME: "rm-portal-bucket"
  MAIL_SERVER: "smtp.office365.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "True"
  MAIL_USE_SSL: "False"
  MAIL_USERNAME: "no-reply@opcito.com"
  MAIL_PASSWORD: "SUas^*_367"
  MAIL_DEFAULT_SENDER: ""
  JWT_SECRET_KEY: ""
  REDIS_HOST: "redis://:88hQbkeupj9yOLeetOGBtnI6X1@redis-master.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://:88hQbkeupj9yOLeetOGBtnI6X1@redis-master.redis.svc.cluster.local:6379"